### ISSUE TITLE
Unsupported: Package level var MyStruct[GenericType] = {instantiation of struct}

### ISSUE THREAD

**Issue by pspencer-arculus** [xhd2015/xgo#357]
Using go 1.24.4. 
To fix build: the instantiation has to be moved to an `init()` or a `Setup` func.
```
go tool xgo test -v ./providers/blockbook
# arculus.com/Arculus-Cloud/types
types/arculus-structs.go:205: cannot use generic type ReqBody[T any] without instantiation
types/arculus-structs.go:250: cannot use generic type ReqBody[T any] without instantiation
types/arculus-structs.go:342: cannot use generic type ReqBody[T any] without instantiation
# arculus.com/Arculus-Cloud/keydb
keydb/keydb.go:44: cannot use generic type task.Tasker[Client any] without instantiation
FAIL    arculus.com/Arculus-Cloud/providers/blockbook [build failed]
FAIL
```

**Comment by pspencer-arculus** [comment]
I refactored my code to make xgo work and I think your project is amazing :)

**Comment by xhd2015** [comment]
Aha, a good point, I think it's related to variable mocking, https://github.com/xhd2015/xgo/blob/master/runtime/test/mock/mock_var/mock_var_test.go

I'll add a test for this and fix it, thanks for feedback!

**Comment by xhd2015** [comment]
However seems this fix breaks other tests:
```
# github.com/xhd2015/xgo/runtime/test/patch/patch_var/generic_return/service
generic_return_test.go:12: expected type argument list
FAIL	github.com/xhd2015/xgo/runtime/test/patch/patch_var/generic_return/service [setup failed]
```

Will have deeper check later.

**Comment by xhd2015** [comment]
fixed and released new tag https://github.com/xhd2015/xgo/releases/tag/v1.1.8

**Comment by pspencer-arculus** [comment]
thanks so much @xhd2015!! Love your framework!

**Comment by pspencer-arculus** [comment]
@xhd2015  Reopening because I still have an error -- I think because my struct instantiation has complex input params like the `F` func. Either that or it has to do with my projects structure.

I attached some code below, but it would be better if I create a test or repo to reproduce this and will send that to you. Thanks again for quickly resolving this!

## Could not revert to previous version of code
```go
var TesterRoutine = task.Routine[gorm.DB]{
	Name:   "TesterRoutine",
	Period: 5 * time.Minute,
	F: func(db *gorm.DB, ctx context.Context, now time.Time) error {
		var data []MyDBTable
		if err := db.Find(&data).Error; err != nil {
			return errors.Annotatef(err, "failed to get my data at time: %s", now)
		}
		return nil
	},
}
```

```
go tool xgo test arculus.com/Arculus-Cloud/providers/blockbook -short
# database/chainlist
database/chainlist/chainlist.go:20: __xgo_var_ref_43_5 redeclared in this block
        database/chainlist/chainlist.go:20[/.xgo/gen/overlay/PROJECT/database/chainlist/chainlist.go:21:26]: other declaration of __xgo_var_ref_43_5
database/chainlist/chainlist.go:20: "utils/task" imported as __xgo_var_ref_43_5 and not used
database/chainlist/chainlist.go:77: undefined: __xgo_var_ref_43_5.Routine
FAIL    providers/blockbook [build failed]
```

## Refactoring to a Setup() func solved the build
```go
var TesterRoutine task.Routine[gorm.DB]

func Setup() {
	TesterRoutine = task.Routine[gorm.DB]{
		Name:   "TesterRoutine",
		Period: 5 * time.Minute,
		F: func(db *gorm.DB, ctx context.Context, now time.Time) error {
			var data []MyDBTable
			if err := db.Find(&data).Error; err != nil {
				return errors.Annotatef(err, "failed to get my data at time: %s", now)
			}
			return nil
		},
	}
}
```

```
go tool xgo test arculus.com/Arculus-Cloud/providers/blockbook -short
ok      arculus.com/Arculus-Cloud/providers/blockbook   0.327s
```

**Comment by xhd2015** [comment]
@pspencer-arculus can you check the code in `.xgo/gen/overlay/PROJECT/database/chainlist/chainlist.go:21`, which is the rewritten content of the original file.

Can give a minimal reproducible example if possible, thanks.

**Comment by pspencer-arculus** [comment]
Check this out in the generated file. Two imports are getting the same generated name, thus conflicting:
```go
package chainlist;import __xgo_var_ref_43_5 "gorm.io/gorm";import __xgo_var_ref_43_5 "arculus.com/Arculus-Cloud/utils/task";import __xgo_var_ref_125_5 "net/http"
```

**Comment by xhd2015** [comment]
The bug was caused by duplicate ref names in the import rewritter, fixed in https://github.com/xhd2015/xgo/pull/360

**Comment by xhd2015** [comment]
released: https://github.com/xhd2015/xgo/releases/tag/v1.1.9
